include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.bak"
    - "**/*.backup"
    - "**/*_bak.*"
    - build/**
    - android/**
    - ios/**
    - web/**
    - windows/**
    - macos/**
    - linux/**

linter:
  rules:
    # avoid_print: false
    # prefer_single_quotes: true
