import 'package:flutter/material.dart';

class AppStrings {
  static const Map<String, Map<String, String>> values = {
    'ar': {
      'appTitle': 'العلامة المائية',
      'saveSuccess': 'تم الحفظ',
      'processedSuccess': 'تمت معالجة وحفظ {count} من أصل {total} صورة بنجاح.',
      'savePath': 'مسار الحفظ',
      'ok': 'حسناً',
      'openFolder': 'فتح المجلد',
      'openFolderError': 'تعذر فتح المجلد',
      'pleaseSelect': 'حدد الصور والشعار أولاً',
      'selectImages': 'الصور',
      'selectLogo': 'الشعار',
      'newSession': 'جلسة جديدة',
      'settings': 'الإعدادات',
      'exit': 'خروج',
      'shareQuoteLabel': 'اكتب اقتباس أو نص ترويجي للمشاركة على صفحات التواصل:',
      'shareQuoteHint': 'مثال: وصل حديثاً تشكيلة مميزة..',
      'quoteHint': 'اكتب اقتباساً للمشاركة',
      'processedByApp': 'تمت معالجة الصور بواسطة Watermark Pro',
      'exitTooltip': 'خروج',
      'settingsTooltip': 'الإعدادات',
      'enlargeLogo': 'تكبير',
      'rotateLogo': 'تدوير',
      'logoOpacity': 'شفافية',
      'savingExporting': 'جاري الحفظ والتصدير {current}/{total}',
      'noImages': 'لا توجد صور',
      'selectedImage': 'الصورة {current} من {total}',
      'dragLogoHint': 'اسحب الشعار لتحريكه',
      'toolsTitle': 'أدوات التعديل',
      'applyToAllTitle': 'تطبيق على الكل',
      'applyToAllOn': 'التعديلات تُطبق على كل الصور',
      'applyToAllOff': 'تعديل كل صورة بشكل مستقل',
      'removeLogoBg': 'إزالة خلفية الشعار',
      'removeLogoBgHint': 'جعل الشعار شفافاً',
      'opacity': 'الشفافية: {value}%',
      'applySave': 'تطبيق وحفظ',
      'settingsTitle': 'الإعدادات',
      'backgroundColor': 'خلفية التطبيق',
      'gradientColor': 'التدرج',
      'selectedColor': 'اللون المحدد: {color}',
      'language': 'اللغة',
      'currentArabic': 'اللغة الحالية: العربية',
      'currentEnglish': 'Current Language: English',
      'changeLanguage': 'تغيير اللغة',
      'aboutTitle': 'حول التطبيق',
      'aboutDescription': 'Watermark Pro هو تطبيق متخصص لإضافة العلامات المائية والشعارات التجارية إلى مجموعة من الصور دفعة واحدة من وحدة التخزين.\n\nأهم وظائف التطبيق:\n1. اختيار عدة صور من الجهاز دفعة واحدة.\n2. اختيار شعار أو لوقو من الجهاز.\n3. دعم صيغ صور الشعار JPG وJPEG وPNG وWEBP. ويُفضّل استخدام PNG أو WEBP للشعارات ذات الخلفية الشفافة.\n4. إزالة خلفية الشعار تلقائياً عند تفعيل الخيار.\n5. التحكم في مكان وحجم وشفافية الشعار.\n6. تطبيق الإعدادات وحفظ الصور الناتجة بسرعة.',
      'version': 'الإصدار: v1.0.0',
      'gradientWhite': 'أبيض ناصع',
      'gradientSky': 'أزرق سمائي',
      'gradientRoyal': 'أزرق ملكي',
      'gradientPurple': 'بنفسجي هادئ',
      'gradientGray': 'رمادي عصري',
      'gradientDark': 'رمادي داكن فاخر',
      'aboutDescriptionTitle': 'حول التطبيق',
      'aboutDescriptionText': 'Watermark Pro هو تطبيق متخصص لإضافة العلامات المائية والشعارات التجارية إلى مجموعة من الصور دفعة واحدة من وحدة التخزين.\n\nأهم وظائف التطبيق:\n1. اختيار عدة صور من الجهاز دفعة واحدة.\n2. اختيار شعار أو لوقو من الجهاز.\n3. دعم صيغ صور الشعار JPG وJPEG وPNG وWEBP. ويُفضّل استخدام PNG أو WEBP للشعارات ذات الخلفية الشفافة.\n4. إزالة خلفية الشعار تلقائياً عند تفعيل الخيار.\n5. التحكم في مكان وحجم وشفافية الشعار.\n6. تطبيق الإعدادات وحفظ الصور الناتجة بسرعة.',
      'versionText': 'الإصدار: v1.0.0',
    },
    'en': {
      'appTitle': 'Watermark Pro',
      'saveSuccess': 'Saved Successfully',
      'processedSuccess': 'Processed and saved {count} of {total} images successfully.',
      'savePath': 'Save path:',
      'ok': 'OK',
      'openFolder': 'Open Folder',
      'openFolderError': 'Unable to open folder',
      'pleaseSelect': 'Please select images and a logo first',
      'selectImages': 'Images',
      'selectLogo': 'Logo',
      'newSession': 'New Session',
      'settings': 'Settings',
      'exit': 'Exit',
      'shareQuoteLabel': 'Write a quote or promotional text to share on social media:',
      'shareQuoteHint': 'Example: New collection just arrived..',
      'quoteHint': 'Enter a quote to share',
      'processedByApp': 'Images processed by Watermark Pro',
      'exitTooltip': 'Exit',
      'settingsTooltip': 'Settings',
      'enlargeLogo': 'Enlarge',
      'rotateLogo': 'Rotate',
      'logoOpacity': 'Opacity',
      'savingExporting': 'Saving and exporting {current}/{total}',
      'noImages': 'No Images',
      'selectedImage': 'Image {current} of {total}',
      'dragLogoHint': 'Drag the logo to move it',
      'toolsTitle': 'Editing Tools',
      'applyToAllTitle': 'Apply to All',
      'applyToAllOn': 'Changes apply to all images',
      'applyToAllOff': 'Customize each image independently',
      'removeLogoBg': 'Remove Logo Background',
      'removeLogoBgHint': 'Make the logo transparent',
      'opacity': 'Opacity: {value}%',
      'applySave': 'Apply & Save',
      'settingsTitle': 'Settings & About',
      'backgroundColor': 'App Background',
      'gradientColor': 'Gradient',
      'selectedColor': 'Selected color: {color}',
      'language': 'Language',
      'currentArabic': 'Current Language: Arabic',
      'currentEnglish': 'Current Language: English',
      'changeLanguage': 'Change Language',
      'aboutTitle': 'About',
      'aboutDescription': 'Watermark Pro is a specialized app for adding watermarks and commercial logos to multiple images at once from device storage.\n\nMain features:\n1. Select multiple images from the device at once.\n2. Select a logo from the device.\n3. Supports JPG, JPEG, PNG, and WEBP logo image formats. PNG or WEBP is recommended for logos with transparent backgrounds.\n4. Automatically remove the logo background when enabled.\n5. Control the logo position, size, and opacity.\n6. Apply the settings and save the processed images quickly.',
      'version': 'Version: v1.0.0',
      'gradientWhite': 'Bright White',
      'gradientSky': 'Sky Blue',
      'gradientRoyal': 'Royal Blue',
      'gradientPurple': 'Calm Purple',
      'gradientGray': 'Modern Gray',
      'gradientDark': 'Luxury Dark Charcoal',
      'aboutDescriptionTitle': 'About the App',
      'aboutDescriptionText': 'Watermark Pro is a specialized app for adding watermarks and commercial logos to multiple images at once from device storage.\n\nMain features:\n1. Select multiple images from the device at once.\n2. Select a logo from the device.\n3. Supports JPG, JPEG, PNG, and WEBP logo image formats. PNG or WEBP is recommended for logos with transparent backgrounds.\n4. Automatically remove the logo background when enabled.\n5. Control the logo position, size, and opacity.\n6. Apply the settings and save the processed images quickly.',
      'versionText': 'Version: v1.0.0',
    },
  };

  static String get(
    BuildContext context,
    String key, {
    Map<String, String>? args,
  }) {
    final language = Localizations.localeOf(context).languageCode;
    var value = values[language]?[key] ?? values['en']?[key] ?? key;

    if (args != null) {
      for (final entry in args.entries) {
        value = value.replaceAll('{${entry.key}}', entry.value);
      }
    }

    return value;
  }
}
